/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Turing;

import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class Turing extends javax.swing.JFrame {

    Execusao exe = new Execusao();// classe de execusao
    LinkedList<Estados> estado = new LinkedList<Estados>(); //Cria lista de Estados

    int quantEstado = 0; // nem sei pra q é 
    boolean fim = false; // saber qual é o estado final
    boolean lado = false;// saber o lado s é esquerdo ou direito true direito false Esqerdo

    /**
     * Creates new form TelaInicial
     */
    public Turing() {
        super("Maquina de Turing Com Uma Fita");//setar nome para o titulo da tela

        initComponents();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jbtCriarTranzicao = new javax.swing.JButton();
        ctfSubstituir = new javax.swing.JFormattedTextField();
        ctfAlfabeto = new javax.swing.JFormattedTextField();
        jcbEstadoSelect = new javax.swing.JComboBox();
        jcbProximoestado = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jrbDireita = new javax.swing.JRadioButton();
        jrbEsquerda = new javax.swing.JRadioButton();
        jcbtranzicoes = new javax.swing.JComboBox();
        jbtExcluirTranzicao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtCriarEstado = new javax.swing.JButton();
        jcbEstado = new javax.swing.JComboBox();
        jtfInicial = new javax.swing.JTextField();
        jrbFinal = new javax.swing.JRadioButton();
        jtfFinal = new javax.swing.JTextField();
        jbtSair = new javax.swing.JButton();
        jbtExecutar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jimNovo = new javax.swing.JMenuItem();
        jimAbrir = new javax.swing.JMenuItem();
        jimSalvar = new javax.swing.JMenuItem();
        jimSalvarComo = new javax.swing.JMenuItem();
        jimCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Estados"));

        jbtCriarTranzicao.setText("Criar Tranzições");
        jbtCriarTranzicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCriarTranzicaoActionPerformed(evt);
            }
        });

        try {
            ctfSubstituir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ctfAlfabeto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("--------->");

        buttonGroup2.add(jrbDireita);
        jrbDireita.setText("Direita");
        jrbDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDireitaActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbEsquerda);
        jrbEsquerda.setText("Esquerda");
        jrbEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEsquerdaActionPerformed(evt);
            }
        });

        jbtExcluirTranzicao.setText("Excluir Transição");
        jbtExcluirTranzicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirTranzicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jcbtranzicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtCriarTranzicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtExcluirTranzicao)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jcbEstadoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ctfAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ctfSubstituir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDireita)
                            .addComponent(jrbEsquerda))
                        .addGap(18, 18, 18)
                        .addComponent(jcbProximoestado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrbDireita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbEsquerda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ctfSubstituir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ctfAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbEstadoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jcbProximoestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCriarTranzicao, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbtranzicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtExcluirTranzicao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Estados"));

        jbtCriarEstado.setText("Criar Estados");
        jbtCriarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCriarEstadoActionPerformed(evt);
            }
        });

        jtfInicial.setEditable(false);

        buttonGroup1.add(jrbFinal);
        jrbFinal.setText("Final");
        jrbFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFinalActionPerformed(evt);
            }
        });

        jtfFinal.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jrbFinal)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCriarEstado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCriarEstado)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jtfInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbFinal))
                .addContainerGap())
        );

        jbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/Delete.png"))); // NOI18N
        jbtSair.setText("Sair");
        jbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSairActionPerformed(evt);
            }
        });

        jbtExecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/dial-a-fix-2.png"))); // NOI18N
        jbtExecutar.setText("Executar");
        jbtExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExecutarActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jimNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jimNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/Cadastrar.gif"))); // NOI18N
        jimNovo.setText("Novo");
        jimNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimNovoActionPerformed(evt);
            }
        });
        jMenu1.add(jimNovo);

        jimAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jimAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/Save.png"))); // NOI18N
        jimAbrir.setText("Abrir");
        jMenu1.add(jimAbrir);

        jimSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jimSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/Load.png"))); // NOI18N
        jimSalvar.setText("Salvar");
        jimSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(jimSalvar);

        jimSalvarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jimSalvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/Load.png"))); // NOI18N
        jimSalvarComo.setText("Salvar Como");
        jimSalvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimSalvarComoActionPerformed(evt);
            }
        });
        jMenu1.add(jimSalvarComo);

        jimCreditos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jimCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNG-24/pc.png"))); // NOI18N
        jimCreditos.setText("Creditos");
        jimCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimCreditosActionPerformed(evt);
            }
        });
        jMenu1.add(jimCreditos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtExecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSair)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jimSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimSalvarComoActionPerformed
        JOptionPane.showMessageDialog(null, "Salvar Como");
    }//GEN-LAST:event_jimSalvarComoActionPerformed

    private void jimSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimSalvarActionPerformed
        JOptionPane.showMessageDialog(null, "Salvar");
    }//GEN-LAST:event_jimSalvarActionPerformed

    private void jbtExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExecutarActionPerformed

        exe.show();


    }//GEN-LAST:event_jbtExecutarActionPerformed

    private void jimNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimNovoActionPerformed
        JOptionPane.showMessageDialog(null, "Novo Arquivo");

    }//GEN-LAST:event_jimNovoActionPerformed

    private void jbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtSairActionPerformed

    private void jimCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimCreditosActionPerformed
        JOptionPane.showMessageDialog(null, "Creditos");

    }//GEN-LAST:event_jimCreditosActionPerformed

    private void jbtCriarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCriarEstadoActionPerformed

        int tipo = 1;

        jcbEstado.addItem("q" + quantEstado);//adicionando item aos estados 
        jcbEstadoSelect.addItem("q" + quantEstado);
        jcbProximoestado.addItem("q" + quantEstado);

        if (quantEstado == 0) {
            tipo = 0;
            jtfInicial.setText("q" + quantEstado);
        } else if (fim && quantEstado != 0) { // testar pra  o estado inical não seja o mesmo q o final 
            tipo = -1;

        }
//         aki em cima testa para q o valor inicial seja o primeiro 
        //s for tipo = 0 ele é o priemiro 
        // s for -1 ele é o ultimo 
        // s for 1 ele é um estado normal 

        estado.add(new Estados(quantEstado, tipo));// criando estados

        System.out.println("q" + estado.get(quantEstado).valor_estado);

        quantEstado++;
//jtlEstados.setSelectionMode("q"+cont);
        //jtaTranzicoes.setText(jtaTranzicoes.getText() +"q"+cont+"\n");
    }//GEN-LAST:event_jbtCriarEstadoActionPerformed

    private void jbtCriarTranzicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCriarTranzicaoActionPerformed
        char direcao;
        if (lado) {// testar a direção 
            direcao = 'D';
        } else {
            direcao = 'E';
        }

        estado.get(jcbEstadoSelect.getSelectedIndex()).trans.add(new Trans(ctfAlfabeto.getText().charAt(0),
                ctfSubstituir.getText().charAt(0),
                direcao, jcbProximoestado.getSelectedIndex()));// adicionando tranzicoes 

        //concatenando as tranzicoes
        String tranzicoes = estado.get(jcbEstadoSelect.getSelectedIndex()).cont
                + ":" + "(q" + jcbEstadoSelect.getSelectedIndex() + ","
                + estado.get(jcbEstadoSelect.getSelectedIndex()).trans.get(estado.get(jcbEstadoSelect.getSelectedIndex()).cont).valor_leitura + ")===>("
                + "q" + jcbEstadoSelect.getSelectedIndex()
                + "," + estado.get(jcbEstadoSelect.getSelectedIndex()).trans.get(estado.get(jcbEstadoSelect.getSelectedIndex()).cont).valor_escrita
                + "," + estado.get(jcbEstadoSelect.getSelectedIndex()).trans.get(estado.get(jcbEstadoSelect.getSelectedIndex()).cont).direcao + ","
                + "q" + estado.get(jcbEstadoSelect.getSelectedIndex()).trans.get(estado.get(jcbEstadoSelect.getSelectedIndex()).cont).proxEstado + ")";

        jcbtranzicoes.addItem(tranzicoes);

        System.out.println(tranzicoes);
        estado.get(jcbEstadoSelect.getSelectedIndex()).cont++;// incrementando as tranzicoes 
        buttonGroup2.clearSelection();// limpando os botoes 
        ctfAlfabeto.setText(null);
        ctfSubstituir.setText(null);
        jrbDireita.setSelected(false);// desmarcar o radio button
        jrbEsquerda.setSelected(false);// desmarcar o radio button


    }//GEN-LAST:event_jbtCriarTranzicaoActionPerformed

    private void jrbFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFinalActionPerformed
        if (fim && quantEstado != 0) {
            jtfFinal.setText("q" + jcbEstado.getSelectedIndex());// setando para o jtextfilde a posicao final
        }
        fim = true;// informar q é o fim 
        buttonGroup1.clearSelection();// limpando o botao fim

    }//GEN-LAST:event_jrbFinalActionPerformed

    private void jbtExcluirTranzicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirTranzicaoActionPerformed

        String trans = String.valueOf(jcbtranzicoes.getSelectedItem());// pegando o  valor todo da jcombox estado selecionado

        int excluirEstado = Integer.parseInt("" + trans.charAt(4));// transformando pra inteiro pois ele estava lendo o valor da tabela ascii

        int excluirTrans = Integer.parseInt("" + trans.charAt(0));

        if (String.valueOf(trans.charAt(5)) != ",") {

            System.out.println("entrou no if 1");

            String test1 = String.valueOf(trans.charAt(4));
            test1 += String.valueOf(trans.charAt(5));
            excluirEstado = Integer.parseInt(test1);

        }
        if (String.valueOf(trans.charAt(1)) != ":") {

            System.out.println("entrou no if 2");

            String test = String.valueOf(trans.charAt(0));
            test += String.valueOf(trans.charAt(1));
            excluirTrans = Integer.parseInt(test);
        }

        System.out.println("saiu do 2 if");

        System.out.println(excluirTrans);

        estado.get(excluirEstado).trans.remove(excluirTrans);
        System.out.println();

        estado.get(jcbEstadoSelect.getSelectedIndex()).cont--;// decrementando o valor das tranzicoes
        //jcbtranzicoes.removeAll();

    }//GEN-LAST:event_jbtExcluirTranzicaoActionPerformed

    private void jrbDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDireitaActionPerformed

        lado = true;

// TODO add your handling code here:
    }//GEN-LAST:event_jrbDireitaActionPerformed

    private void jrbEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEsquerdaActionPerformed
        lado = false;
// TODO add your handling code here:
    }//GEN-LAST:event_jrbEsquerdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField ctfAlfabeto;
    private javax.swing.JFormattedTextField ctfSubstituir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtCriarEstado;
    private javax.swing.JButton jbtCriarTranzicao;
    private javax.swing.JButton jbtExcluirTranzicao;
    private javax.swing.JButton jbtExecutar;
    private javax.swing.JButton jbtSair;
    private javax.swing.JComboBox jcbEstado;
    private javax.swing.JComboBox jcbEstadoSelect;
    private javax.swing.JComboBox jcbProximoestado;
    private javax.swing.JComboBox jcbtranzicoes;
    private javax.swing.JMenuItem jimAbrir;
    private javax.swing.JMenuItem jimCreditos;
    private javax.swing.JMenuItem jimNovo;
    private javax.swing.JMenuItem jimSalvar;
    private javax.swing.JMenuItem jimSalvarComo;
    private javax.swing.JRadioButton jrbDireita;
    private javax.swing.JRadioButton jrbEsquerda;
    private javax.swing.JRadioButton jrbFinal;
    private javax.swing.JTextField jtfFinal;
    private javax.swing.JTextField jtfInicial;
    // End of variables declaration//GEN-END:variables
}
